# Generated by Django 5.2.17 on 2026-09-18 16:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeocodeCache',
            fields=[
                ('key', models.CharField(max_length=512, primary_key=True, serialize=False)),
                ('payload', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('input', models.JSONField()),
                ('result', models.JSONField()),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
